FROM google/cloud-sdk:550.0.0

# install helm
RUN curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4 | bash

# install vim
RUN apt-get update && apt-get install -y vim jq kubectl unzip

# install terraform
RUN curl -fsSL https://releases.hashicorp.com/terraform/1.10.4/terraform_1.10.4_linux_amd64.zip -o terraform.zip \
  && unzip terraform.zip \
  && mv terraform /usr/local/bin/ \
  && rm terraform.zip
